module ru.demo.investmentapp {
        requires javafx.controls;
        requires javafx.fxml;
        requires jakarta.persistence;
        requires org.hibernate.orm.core;
        requires java.naming;
        requires java.desktop;
        requires javafx.swing;
        requires org.hibernate.validator;
        requires org.postgresql.jdbc;
        requires itextpdf;
        opens ru.demo.investmentapp to javafx.fxml;
        opens ru.demo.investmentapp.model to org.hibernate.orm.core, javafx.base;
        exports ru.demo.investmentapp;
        exports ru.demo.investmentapp.controller;
        opens ru.demo.investmentapp.controller to javafx.fxml;
        opens ru.demo.investmentapp.util to org.hibernate.orm.core;
        exports ru.demo.investmentapp.controller.Account;
        opens ru.demo.investmentapp.controller.Account to javafx.fxml;
        exports ru.demo.investmentapp.controller.Client;
        opens ru.demo.investmentapp.controller.Client to javafx.fxml;
        exports ru.demo.investmentapp.controller.Commission;
        opens ru.demo.investmentapp.controller.Commission to javafx.fxml;
        exports ru.demo.investmentapp.controller.CompanyInfo;
        opens ru.demo.investmentapp.controller.CompanyInfo to javafx.fxml;
        exports ru.demo.investmentapp.controller.Instrument;
        opens ru.demo.investmentapp.controller.Instrument to javafx.fxml;
        exports ru.demo.investmentapp.controller.InvestmentStrategy;
        opens ru.demo.investmentapp.controller.InvestmentStrategy to javafx.fxml;
        exports ru.demo.investmentapp.controller.MarketData;
        opens ru.demo.investmentapp.controller.MarketData to javafx.fxml;
        exports ru.demo.investmentapp.controller.Portfolio;
        opens ru.demo.investmentapp.controller.Portfolio to javafx.fxml;
        exports ru.demo.investmentapp.controller.PortfolioPosition;
        opens ru.demo.investmentapp.controller.PortfolioPosition to javafx.fxml;
        exports ru.demo.investmentapp.controller.PortfolioStrategy;
        opens ru.demo.investmentapp.controller.PortfolioStrategy to javafx.fxml;
        exports ru.demo.investmentapp.controller.Report;
        opens ru.demo.investmentapp.controller.Report to javafx.fxml;
        exports ru.demo.investmentapp.controller.Role;
        opens ru.demo.investmentapp.controller.Role to javafx.fxml;
        exports ru.demo.investmentapp.controller.Transaction;
        opens ru.demo.investmentapp.controller.Transaction to javafx.fxml;
        exports ru.demo.investmentapp.controller.User;
        opens ru.demo.investmentapp.controller.User to javafx.fxml;
}